image: debian:unstable-slim

build:
  artifacts:
    paths:
      - pocket-reform-sysctl-fw/build/sysctl.uf2
      - scripts/update-sysctl-firmware.sh
      - pocket-reform-keyboard-fw/pocket-hid/build/pocket-hid.uf2
  script: |
    set -x
    export SOURCE_ROOT="$PWD"
    ./install-fw-dependencies.sh
    # use the timestamp of the latest git commit to set reproducible S_D_E
    if [ -z ${SOURCE_DATE_EPOCH:+x} ] && git -C . rev-parse 2>/dev/null; then
      SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)
    fi
    # check if the current commit is tagged or otherwise use the git hash
    if git describe >/dev/null 2>&1 && [ "$(git describe --abbrev=0)" = "$(git describe)" ]; then
      VERSION="$(git describe --abbrev=0 | tr -d -)"
    else
      VERSION="g$(git rev-parse --short=7 HEAD)"
    fi
    export PICO_SDK_PATH="$SOURCE_ROOT/pico-sdk"
    cd "$SOURCE_ROOT/pocket-reform-sysctl-fw"
    mkdir -p build
    cd build
    cmake ..
    make -j $(nproc)
    cd "$SOURCE_ROOT/pocket-reform-keyboard-fw/pocket-hid"
    mkdir -p build
    cd build
    cmake -DFAMILY=rp2040 ..
    make -j $(nproc)
